
name: Build & Deploy

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying
        uses: appleboy/ssh-action@master
        with:
          script_stop: true
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USER}}

          script: |
            cd /var/www/app-janice-davila
            git pull
            echo 'npm install adonis...'
            yarn
            echo 'npm install nextjs...'
            cd public
            yarn
            echo 'building...'
            cd ..
            yarn build
            (pm2 delete all || true)
            pm2 start npm --name 'app-janice'--cwd '/var/www/app-janice-davila' -- start
            echo 'app started successfully with pm2'


